### ISSUE TITLE
question about running the run_training.py

### ISSUE THREAD

**Issue by watsom866** [zsyzzsoft/co-mod-gan#36]
Hi, thanks for sharing. When I run the run_training.py, it generates an error.
dnnlib: Running training.training_loop.training_loop() on localhost...
Streaming data using training.dataset.TFRecordDataset...
Traceback (most recent call last):
  File "run_training.py", line 150, in <module>
    main()
  File "run_training.py", line 145, in main
    run(**vars(args))
  File "run_training.py", line 71, in run
    dnnlib.submit_run(**kwargs)
AssertionError
Please help me, thanks so much.

**Comment by zsyzzsoft** [comment]
Can you share the full log?
