### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by mxgbs** [zsyzzsoft/co-mod-gan#55]
Hi, 

I tried to run the example and get following error. Could you please help with it? Thank you.

Setting up TensorFlow plugin "fused_bias_act.cu": Preprocessing... Compiling... Loading... Failed!
Traceback (most recent call last):
  File "run_generator.py", line 34, in <module>
    main()
  File "run_generator.py", line 31, in main
    generate(**vars(args))
  File "run_generator.py", line 14, in generate
    _, _, Gs = misc.load_pkl(checkpoint)
  File "/local/mnt2/workspace2/yandeng/co-mod-gan/training/misc.py", line 30, in load_pkl
    return pickle.load(file, encoding='latin1')
  File "/local/mnt2/workspace2/yandeng/co-mod-gan/dnnlib/tflib/network.py", line 297, in __setstate__
    self._init_graph()
  File "/local/mnt2/workspace2/yandeng/co-mod-gan/dnnlib/tflib/network.py", line 154, in _init_graph
    out_expr = self._build_func(*self.input_templates, **build_kwargs)
  File "<string>", line 383, in G_synthesis_RegionGAN
  File "<string>", line 347, in E_fromrgb
  File "<string>", line 68, in apply_bias_act
  File "/local/mnt2/workspace2/yandeng/co-mod-gan/dnnlib/tflib/ops/fused_bias_act.py", line 68, in fused_bias_act
    return impl_dict[impl](x=x, b=b, axis=axis, act=act, alpha=alpha, gain=gain)
  File "/local/mnt2/workspace2/yandeng/co-mod-gan/dnnlib/tflib/ops/fused_bias_act.py", line 122, in _fused_bias_act_cuda
    cuda_kernel = _get_plugin().fused_bias_act
  File "/local/mnt2/workspace2/yandeng/co-mod-gan/dnnlib/tflib/ops/fused_bias_act.py", line 16, in _get_plugin
    return custom_ops.get_plugin(os.path.splitext(__file__)[0] + '.cu')
  File "/local/mnt2/workspace2/yandeng/co-mod-gan/dnnlib/tflib/custom_ops.py", line 159, in get_plugin
    plugin = tf.load_op_library(bin_file)
  File "/local/mnt2/workspace2/yandeng/anaconda3/envs/comod/lib/python3.6/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /local/mnt2/workspace2/yandeng/co-mod-gan/dnnlib/tflib/_cudacache/fused_bias_act_3983cfc3f38164c8a38c81bd423d1fe1.so: undefined symbol: _ZN10tensorflow12OpDefBuilder6OutputESs

**Comment by zsyzzsoft** [comment]
What is your tf version?

**Comment by ImmortalSdm** [comment]
> Hi,
> 
> I tried to run the example and get following error. Could you please help with it? Thank you.
> 
> Setting up TensorFlow plugin "fused_bias_act.cu": Preprocessing... Compiling... Loading... Failed! Traceback (most recent call last): File "run_generator.py", line 34, in main() File "run_generator.py", line 31, in main generate(**vars(args)) File "run_generator.py", line 14, in generate _, _, Gs = misc.load_pkl(checkpoint) File "/local/mnt2/workspace2/yandeng/co-mod-gan/training/misc.py", line 30, in load_pkl return pickle.load(file, encoding='latin1') File "/local/mnt2/workspace2/yandeng/co-mod-gan/dnnlib/tflib/network.py", line 297, in **setstate** self._init_graph() File "/local/mnt2/workspace2/yandeng/co-mod-gan/dnnlib/tflib/network.py", line 154, in _init_graph out_expr = self._build_func(*self.input_templates, **build_kwargs) File "", line 383, in G_synthesis_RegionGAN File "", line 347, in E_fromrgb File "", line 68, in apply_bias_act File "/local/mnt2/workspace2/yandeng/co-mod-gan/dnnlib/tflib/ops/fused_bias_act.py", line 68, in fused_bias_act return impl_dict[impl](x=x, b=b, axis=axis, act=act, alpha=alpha, gain=gain) File "/local/mnt2/workspace2/yandeng/co-mod-gan/dnnlib/tflib/ops/fused_bias_act.py", line 122, in _fused_bias_act_cuda cuda_kernel = _get_plugin().fused_bias_act File "/local/mnt2/workspace2/yandeng/co-mod-gan/dnnlib/tflib/ops/fused_bias_act.py", line 16, in _get_plugin return custom_ops.get_plugin(os.path.splitext(**file**)[0] + '.cu') File "/local/mnt2/workspace2/yandeng/co-mod-gan/dnnlib/tflib/custom_ops.py", line 159, in get_plugin plugin = tf.load_op_library(bin_file) File "/local/mnt2/workspace2/yandeng/anaconda3/envs/comod/lib/python3.6/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library lib_handle = py_tf.TF_LoadLibrary(library_filename) tensorflow.python.framework.errors_impl.NotFoundError: /local/mnt2/workspace2/yandeng/co-mod-gan/dnnlib/tflib/_cudacache/fused_bias_act_3983cfc3f38164c8a38c81bd423d1fe1.so: undefined symbol: _ZN10tensorflow12OpDefBuilder6OutputESs

You can change line 130 in custom_ops.py as below:

`compile_opts += ' --compiler-options \'-fPIC -D_GLIBCXX_USE_CXX11_ABI=1\''`

the official StyleGAN2 repo gives the solution.
